// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdqLQwt5DkUkX4ypRlWmH4ZSAS2Z7LZDE',
    appId: '1:598164158629:web:6de4fe5eac96b34d2a754c',
    messagingSenderId: '598164158629',
    projectId: 'writeit-e7e5b',
    authDomain: 'writeit-e7e5b.firebaseapp.com',
    storageBucket: 'writeit-e7e5b.firebasestorage.app',
    measurementId: 'G-Q2TYFMBBKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcrLxq-dP2iWb9K3ylGpE3uWAkHIcTvAA',
    appId: '1:598164158629:android:6579e25bb2bdd1e22a754c',
    messagingSenderId: '598164158629',
    projectId: 'writeit-e7e5b',
    storageBucket: 'writeit-e7e5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQUgGnpK0usg23CaQyoBPx-_C7a1HzyeY',
    appId: '1:598164158629:ios:5cb0822378a457152a754c',
    messagingSenderId: '598164158629',
    projectId: 'writeit-e7e5b',
    storageBucket: 'writeit-e7e5b.firebasestorage.app',
    iosBundleId: 'com.example.writeit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQUgGnpK0usg23CaQyoBPx-_C7a1HzyeY',
    appId: '1:598164158629:ios:5cb0822378a457152a754c',
    messagingSenderId: '598164158629',
    projectId: 'writeit-e7e5b',
    storageBucket: 'writeit-e7e5b.firebasestorage.app',
    iosBundleId: 'com.example.writeit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdqLQwt5DkUkX4ypRlWmH4ZSAS2Z7LZDE',
    appId: '1:598164158629:web:a6dd1f0470fd4f0a2a754c',
    messagingSenderId: '598164158629',
    projectId: 'writeit-e7e5b',
    authDomain: 'writeit-e7e5b.firebaseapp.com',
    storageBucket: 'writeit-e7e5b.firebasestorage.app',
    measurementId: 'G-4ZJXP9C826',
  );
}
